version: "3"

services:
  graphql-explorer:
    build: .
    environment:
      - GRAPHQL_ENDPOINT=http://localhost:5677/graphql
      - ACCESS_TOKEN_URL=/token.json
      - ACCESS_TOKEN_JSON_PATH=data.access_token
    ports:
      - 5677:5677

  build-dist:
    build:
      context: .
      dockerfile: Dockerfile.dist
    volumes:
      - .:/app

  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8080:80
    volumes:
      - .:/var/www

